# Generated by Django 5.2.4 on 2026-03-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountgroup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='accounts.accountgroup')),
            ],
            options={
                'db_table': 'AccountCategories',
                'ordering': ['id'],
            },
        ),
    ]
