# Generated by Django 5.2.4 on 2026-03-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountClass',
        ),
    ]
