# Generated by Django 5.2.4 on 2026-03-04 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accountclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.accountclass')),
            ],
            options={
                'db_table': 'Accounts',
                'ordering': ['id'],
            },
        ),
    ]
