# Generated by Django 5.2.11 on 2026-05-30 07:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('v_type', models.CharField(choices=[('PV', 'Payment'), ('RV', 'Receipt'), ('JV', 'Journal')], help_text='Receipt / Payment / Journal', max_length=2)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('tag', models.CharField(blank=True, help_text='Grouping label, e.g. Overheads / Payroll', max_length=40)),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_recurring', models.BooleanField(default=False)),
                ('frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fin_voucher_template',
                'ordering': ['v_type', 'name'],
                'indexes': [models.Index(fields=['v_type'], name='idx_tpl_vtype'), models.Index(fields=['is_active'], name='idx_tpl_active')],
            },
        ),
        migrations.CreateModel(
            name='VoucherTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('account', models.ForeignKey(help_text='Locked account from the Chart of Accounts', on_delete=django.db.models.deletion.PROTECT, related_name='template_lines', to='accounts.account')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='templates.vouchertemplate')),
            ],
            options={
                'db_table': 'fin_voucher_template_line',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
