import React from 'react';
import { COMPANY } from '../../services/mockData';
import { todayLabel } from '../../utils/reportHelpers';

// The printable sheet wrapper used by every report. The id is what the
// print/PDF export targets.
export function ReportSheet({ id, kicker, asOf, children }) {
  return (
    <article className="rp-sheet" id={id}>
      <header className="rp-masthead">
        <div className="rp-mast-left">
          <span className="rp-mast-kicker">{kicker}</span>
          <h2 className="rp-mast-title">{COMPANY.name}</h2>
        </div>
        <div className="rp-mast-meta">
          <span>{asOf}</span>
          <span className="rp-mast-cur">{COMPANY.currency}</span>
        </div>
      </header>

      {children}

      <footer className="rp-foot">
        <span>Generated by FinTrack</span>
        <span>Prepared {todayLabel()}</span>
      </footer>
    </article>
  );
}

// account-type tag
export function TypeTag({ type }) {
  const t = (type || '').toLowerCase();
  return <span className={`rp-tag t-${t}`}>{type}</span>;
}

// loading skeleton rows
export function SkeletonRows({ cols = 5, rows = 6 }) {
  return (
    <tbody>
      {[...Array(rows)].map((_, i) => (
        <tr key={i} className="rp-skel-row">
          {[...Array(cols)].map((__, j) => (
            <td key={j}><span className="rp-skel" style={{ animationDelay: `${(i + j) * 60}ms` }} /></td>
          ))}
        </tr>
      ))}
    </tbody>
  );
}
