# Generated by Django 5.2.12 on 2026-04-28 21:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Rate vs base currency (e.g. 1 USD = 278.5 PKR)', max_digits=18)),
                ('is_base', models.BooleanField(default=False, help_text='Only ONE currency should be base')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'db_table': 'fin_currency',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VoucherHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('v_type', models.CharField(choices=[('PV', 'Payment Voucher'), ('RV', 'Receipt Voucher'), ('JV', 'Journal Voucher')], max_length=2)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, help_text='Cheque no / invoice no / reference doc', max_length=100)),
                ('narration', models.TextField(blank=True, help_text='Overall description of transaction')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18)),
                ('is_reversal', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('recurring_end_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, help_text='Placeholder – swap for FK to auth.User', null=True)),
                ('approved_by', models.IntegerField(blank=True, help_text='Placeholder – swap for FK to auth.User', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(blank=True, help_text='Leave blank for base currency', null=True, on_delete=django.db.models.deletion.PROTECT, to='vouchers.currency')),
                ('recurring_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_children', to='vouchers.voucherheader')),
                ('reversed_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='vouchers.voucherheader')),
            ],
            options={
                'db_table': 'fin_voucher_header',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(help_text='FK to coa.Account – IntegerField until COA app is ready')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount_fc', models.DecimalField(blank=True, decimal_places=2, help_text='Amount in foreign currency before conversion', max_digits=18, null=True)),
                ('cost_center', models.CharField(blank=True, help_text='Optional cost center for management reporting', max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('currency', models.ForeignKey(blank=True, help_text='Original transaction currency (if != base)', null=True, on_delete=django.db.models.deletion.PROTECT, to='vouchers.currency')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vouchers.voucherheader')),
            ],
            options={
                'db_table': 'fin_voucher_detail',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('last_generated', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('template_voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='vouchers.voucherheader')),
            ],
            options={
                'db_table': 'fin_recurring_schedule',
            },
        ),
        migrations.AddIndex(
            model_name='voucherheader',
            index=models.Index(fields=['date'], name='fin_voucher_date_e132b6_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherheader',
            index=models.Index(fields=['v_type'], name='fin_voucher_v_type_d628ff_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherheader',
            index=models.Index(fields=['status'], name='fin_voucher_status_e954df_idx'),
        ),
    ]
