# Generated by Django 6.0.4 on 2026-05-31 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_link_coa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Characters < > { } \' " \\ are not allowed.', regex='^[^<>{}\\"\\\\]*$')]),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Characters < > { } \' " \\ are not allowed.', regex='^[^<>{}\\"\\\\]*$')]),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Optional cost center for management reporting', max_length=50, validators=[django.core.validators.RegexValidator(message='Characters < > { } \' " \\ are not allowed.', regex='^[^<>{}\\"\\\\]*$')]),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='description',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Characters < > { } \' " \\ are not allowed.', regex='^[^<>{}\\"\\\\]*$')]),
        ),
        migrations.AlterField(
            model_name='voucherheader',
            name='narration',
            field=models.TextField(blank=True, help_text='Overall description of this transaction', validators=[django.core.validators.RegexValidator(message='Characters < > { } \' " \\ are not allowed.', regex='^[^<>{}\\"\\\\]*$')]),
        ),
        migrations.AlterField(
            model_name='voucherheader',
            name='reference',
            field=models.CharField(blank=True, help_text='Cheque no / Invoice no / Reference doc', max_length=100, validators=[django.core.validators.RegexValidator(message='Characters < > { } \' " \\ are not allowed.', regex='^[^<>{}\\"\\\\]*$')]),
        ),
    ]
