# Generated by Django 5.2.12 on 2026-04-30 10:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed'), ('DELETED', 'Deleted (soft)')], max_length=10)),
                ('performed_by', models.IntegerField(blank=True, help_text='Placeholder → FK to auth.User when ready', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('snapshot', models.JSONField(default=dict, help_text='JSON snapshot of voucher at time of action')),
            ],
            options={
                'db_table': 'fin_voucher_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='voucherheader',
            new_name='idx_vh_date',
            old_name='fin_voucher_date_e132b6_idx',
        ),
        migrations.RenameIndex(
            model_name='voucherheader',
            new_name='idx_vh_vtype',
            old_name='fin_voucher_v_type_d628ff_idx',
        ),
        migrations.RenameIndex(
            model_name='voucherheader',
            new_name='idx_vh_status',
            old_name='fin_voucher_status_e954df_idx',
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='times_generated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Characters  < > { } \' " \\  are not allowed.', regex='^[^<>{}\\\'\\"\\\\]*$')]),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='How many base-currency units = 1 of this currency', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Characters  < > { } \' " \\  are not allowed.', regex='^[^<>{}\\\'\\"\\\\]*$')]),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='account_id',
            field=models.IntegerField(help_text='PK of coa.Account — IntegerField until COA app is integrated'),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Optional cost center for management reporting', max_length=50, validators=[django.core.validators.RegexValidator(message='Characters  < > { } \' " \\  are not allowed.', regex='^[^<>{}\\\'\\"\\\\]*$')]),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Original currency before conversion to base', null=True, on_delete=django.db.models.deletion.PROTECT, to='vouchers.currency'),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='description',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Characters  < > { } \' " \\  are not allowed.', regex='^[^<>{}\\\'\\"\\\\]*$')]),
        ),
        migrations.AlterField(
            model_name='voucherheader',
            name='approved_by',
            field=models.IntegerField(blank=True, help_text='Placeholder → swap for FK to auth.User when ready', null=True),
        ),
        migrations.AlterField(
            model_name='voucherheader',
            name='created_by',
            field=models.IntegerField(blank=True, help_text='Placeholder → swap for FK to auth.User when ready', null=True),
        ),
        migrations.AlterField(
            model_name='voucherheader',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Leave blank to use base currency', null=True, on_delete=django.db.models.deletion.PROTECT, to='vouchers.currency'),
        ),
        migrations.AlterField(
            model_name='voucherheader',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='voucherheader',
            name='narration',
            field=models.TextField(blank=True, help_text='Overall description of this transaction', validators=[django.core.validators.RegexValidator(message='Characters  < > { } \' " \\  are not allowed.', regex='^[^<>{}\\\'\\"\\\\]*$')]),
        ),
        migrations.AlterField(
            model_name='voucherheader',
            name='reference',
            field=models.CharField(blank=True, help_text='Cheque no / Invoice no / Reference doc', max_length=100, validators=[django.core.validators.RegexValidator(message='Characters  < > { } \' " \\  are not allowed.', regex='^[^<>{}\\\'\\"\\\\]*$')]),
        ),
        migrations.AlterField(
            model_name='voucherheader',
            name='reversed_voucher',
            field=models.ForeignKey(blank=True, help_text='Original voucher this entry reverses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='vouchers.voucherheader'),
        ),
        migrations.AlterField(
            model_name='voucherheader',
            name='voucher_no',
            field=models.CharField(editable=False, help_text='Auto-generated. Format: PV-2025-00001', max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='recurringschedule',
            index=models.Index(fields=['next_due_date', 'is_active'], name='idx_rs_due_active'),
        ),
        migrations.AddIndex(
            model_name='voucherdetail',
            index=models.Index(fields=['account_id'], name='idx_vd_account'),
        ),
        migrations.AddIndex(
            model_name='voucherdetail',
            index=models.Index(fields=['account_id', 'header'], name='idx_vd_account_header'),
        ),
        migrations.AddIndex(
            model_name='voucherheader',
            index=models.Index(fields=['date', 'v_type'], name='idx_vh_date_vtype'),
        ),
        migrations.AddIndex(
            model_name='voucherheader',
            index=models.Index(fields=['date', 'status'], name='idx_vh_date_status'),
        ),
        migrations.AddIndex(
            model_name='voucherheader',
            index=models.Index(fields=['is_active'], name='idx_vh_active'),
        ),
        migrations.AddField(
            model_name='voucherauditlog',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='vouchers.voucherheader'),
        ),
    ]
