# Generated by Django 5.2.11 on 2026-05-31 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('actor_name', models.CharField(blank=True, default='System', max_length=150)),
                ('actor_role', models.CharField(blank=True, default='', max_length=20)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('applied', 'Applied'), ('generated', 'Generated'), ('login', 'Signed in'), ('logout', 'Signed out'), ('login_failed', 'Failed sign-in'), ('role_changed', 'Role changed'), ('status_changed', 'Status changed')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(db_index=True, max_length=40)),
                ('entity_id', models.CharField(blank=True, default='', max_length=40)),
                ('entity_label', models.CharField(blank=True, default='', max_length=200)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fin_audit_event',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='fin_audit_e_entity__af4336_idx'), models.Index(fields=['actor_id'], name='fin_audit_e_actor_i_b1c8c9_idx'), models.Index(fields=['action'], name='fin_audit_e_action_1e9ad1_idx')],
            },
        ),
    ]
