# Generated by Django 6.0.4 on 2026-05-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('applied', 'Applied'), ('generated', 'Generated'), ('login', 'Signed in'), ('logout', 'Signed out'), ('login_failed', 'Failed sign-in'), ('role_changed', 'Role changed'), ('status_changed', 'Status changed'), ('password_reset', 'Password reset'), ('password_changed', 'Password changed')], db_index=True, max_length=20),
        ),
    ]
